import { NgModule } from '@angular/core';

import {
    MatPaginatorModule, MatButtonModule, MatFormFieldModule, MatIconModule, MatInputModule, MatSelectModule, MatTableModule
    // MatAutocompleteModule, MatBadgeModule, MatBottomSheetModule, MatButtonModule,
    // MatButtonToggleModule, MatCardModule, MatCheckboxModule, MatChipsModule, MatDatepickerModule,
    // MatDialogModule, MatDividerModule, MatExpansionModule, MatFormFieldModule, MatGridListModule,
    // MatIconModule, MatInputModule, MatListModule, MatMenuModule, 
    // MatProgressBarModule, MatProgressSpinnerModule, MatRadioModule, MatRippleModule, MatSelectModule,
    // MatSidenavModule, MatSliderModule, MatSlideToggleModule, MatSnackBarModule, MatSortModule,
    // MatStepperModule, MatTableModule, MatTabsModule, MatToolbarModule, MatTooltipModule, MatTreeModule
} from '@angular/material';
import { MatMomentDateModule } from '@angular/material-moment-adapter';

@NgModule({
    imports: [
        // MatAutocompleteModule,
        // MatBadgeModule,
        // MatBottomSheetModule,
        MatButtonModule,
        // MatButtonToggleModule,
        // MatCardModule,
        // MatCheckboxModule,
        // MatChipsModule,
        // MatDatepickerModule,
        // MatDialogModule,
        // MatDividerModule,
        // MatExpansionModule,
        MatFormFieldModule,
        // MatGridListModule,
        MatIconModule,
        MatInputModule,
        // MatListModule,
        // MatMenuModule,
        // MatMomentDateModule,
        MatPaginatorModule,
        // MatProgressBarModule,
        // MatProgressSpinnerModule,
        // MatRadioModule,
        // MatRippleModule,
        MatSelectModule,
        // MatSidenavModule,
        // MatSlideToggleModule,
        // MatSliderModule,
        // MatSnackBarModule,
        // MatSortModule,
        // MatStepperModule,
        MatTableModule,
        // MatTabsModule,
        // MatToolbarModule,
        // MatTooltipModule,
        // MatTreeModule
    ],
    exports: [
        // MatAutocompleteModule,
        // MatBadgeModule,
        // MatBottomSheetModule,
        MatButtonModule,
        // MatButtonToggleModule,
        // MatCardModule,
        // MatCheckboxModule,
        // MatChipsModule,
        // MatDatepickerModule,
        // MatDialogModule,
        // MatDividerModule,
        // MatExpansionModule,
        MatFormFieldModule,
        // MatGridListModule,
        MatIconModule,
        MatInputModule,
        // MatListModule,
        // MatMenuModule,
        // MatMomentDateModule,
        MatPaginatorModule,
        // MatProgressBarModule,
        // MatProgressSpinnerModule,
        // MatRadioModule,
        // MatRippleModule,
        MatSelectModule,
        // MatSidenavModule,
        // MatSlideToggleModule,
        // MatSliderModule,
        // MatSnackBarModule,
        // MatSortModule,
        // MatStepperModule,
        MatTableModule,
        // MatTabsModule,
        // MatToolbarModule,
        // MatTooltipModule,
        // MatTreeModule
    ]
})
export class MaterialModule {
}
